name: docker release


on:
  # only on tag pushes
  push:
    branches-ignore:
      - '**'
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      tag:
        description: 'the tag to publish and possibly overwrite'
        default: 'dev'
        required: false


jobs:
  image-publish:
    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/image-publish.yml@v1.16
    permissions: # for GITHUB_TOKEN
      packages: write
    with:
      image_registry: ghcr.io
      image_namespace: observation-management-service
      image_name: ewms-workflow-management-service
      mode: 'BUILD'
      extra_build_tag: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || '' }}
