name: wipac ci/cd

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'


env:
  CI_DOCKER_IMAGE_W_TAG: wms/test:local
  MONGODB_HOST: localhost
  MONGODB_PORT: 27017
  REST_HOST: localhost  # the server should connect to 0.0.0.0
  REST_PORT: 8080
  MQS_ADDRESS: http://localhost:8081
  #
  REST_OPENAPI_SPEC_FPATH: "schema/rest/openapi_compiled.json"
  DB_JSONSCHEMA_DIR: "schema/db"
  #
  WORKFLOW_MQ_ACTIVATOR_DELAY: 2  # need to define for pytests
  WORKFLOW_MQ_ACTIVATOR_MQS_RETRY_WAIT: 10  # ''
  TASKFORCE_LAUNCH_CONTROL_DELAY: 2  # ''



jobs:

  py-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: versions
        uses: WIPACrepo/wipac-dev-py-versions-action@v2.5


  #############################################################################
  # LINTERS
  #############################################################################

  flake8:
    needs: [ py-versions ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version:
            ${{ matrix.py3 }}
      - uses: WIPACrepo/wipac-dev-flake8-action@v1.2

  mypy:
    needs: [ py-versions ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py3 }}
      - uses: WIPACrepo/wipac-dev-mypy-action@v2.0


  #############################################################################
  # PACKAGING
  #############################################################################

  writable-branch-detect:
    runs-on: ubuntu-latest
    outputs:
      OKAY: ${{ steps.detect.outputs.OKAY }}
    steps:
      - name: is this a bot-writable branch?
        id: detect
        # dependabot can't access normal secrets
        #   & don't run non-branch triggers (like tags)
        run: |
          set -euo pipefail
          if [[ \
              ${{github.actor}} != 'dependabot[bot]' && \
              ${{github.ref_type}} == 'branch' \
          ]]; then
            echo "OKAY=true" >> "$GITHUB_OUTPUT"
            echo "yes, this branch is compatible"
          else
            echo "OKAY=false" >> "$GITHUB_OUTPUT"
            echo "no, this branch is incompatible"
          fi

  py-setup:
    needs: [ writable-branch-detect ]
    runs-on: ubuntu-latest
    steps:
      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
        uses: WIPACrepo/wipac-dev-py-setup-action@v3.1
        with:
          base-keywords: WIPAC IceCube "Observation Management Service" "Event Workflow Management Service"

  py-dependencies:
    needs: [ writable-branch-detect ]
    runs-on: ubuntu-latest
    steps:
      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
        uses: docker/setup-buildx-action@v2
      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          tags: wms:py-dep-this
          load: true
      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
        uses: WIPACrepo/wipac-dev-py-dependencies-action@v2.1


  #############################################################################
  # FORMATTER
  #############################################################################

  code-format:
    runs-on: ubuntu-latest
    steps:
      - if: github.actor != 'dependabot[bot]'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # fyi, dependabot can't access normal secrets
      - if: github.actor != 'dependabot[bot]'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          # check git status
          git fetch
          if [[ $(git status -sb | grep behind) ]]; then
            echo "this commit is not the most recent on this branch -- rest of action will be skipped"
            exit 0
          fi
          
          # use literal collection syntax, see https://docs.astral.sh/ruff/rules/unnecessary-collection-call/
          pip install ruff
          ruff check --select C408 --fix . --unsafe-fixes
          
          # push
          git add . || true
          git commit -m "<bot> auto code format file(s)" || true
          git push || true


  ############################################################################
  # AUTO-GENERATION
  #############################################################################

  schema-modifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: WIPACrepo/wipac-dev-json-schema-action@v2.0
        with:
          rest_openapi_paths_dir: "schema-precompiled/paths"
          rest_openapi_base_fpath: "schema-precompiled/openapi_prebuild.json"
          rest_openapi_dest_fpath: "wms/${{ env.REST_OPENAPI_SPEC_FPATH }}"
          db_jsonschema_dir: "wms/${{ env.DB_JSONSCHEMA_DIR }}"
          version: 1

  api-documentation:
    needs: [ schema-modifications ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # fyi, dependabot can't access normal secrets
      - uses: WIPACrepo/wipac-dev-openapi-docs-action@main
        with:
          openapi_fpath: "wms/${{ env.REST_OPENAPI_SPEC_FPATH }}"


  ############################################################################
  # TESTS
  #############################################################################

  test-build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=min
          file: Dockerfile
          tags: ${{ env.CI_DOCKER_IMAGE_W_TAG }}

  integration-test-full-wms-workflow:
    needs: [ py-versions, schema-modifications ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
    services:
      mongo:
        image: bitnami/mongodb:4
        ports:
          - 27017:27017
        env:
          MONGODB_REPLICA_SET_MODE: primary
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py3 }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          # cache-to: type=gha,mode=min
          file: Dockerfile
          tags: ${{ env.CI_DOCKER_IMAGE_W_TAG }}
          load: true
      - run: |
          pip install .[tests]
      - name: test (run servers in background)
        run: |
          python tests/integration/dummy_mqs.py &> ./dummy_mqs.out &
          
          # this needs to be in the same step b/c shell exits when step is done
          docker run --network='host' --rm --name rest \
            --env MONGODB_HOST="${{ env.MONGODB_HOST }}" \
            --env MONGODB_PORT="${{ env.MONGODB_PORT }}" \
            --env REST_HOST="${{ env.REST_HOST }}" \
            --env REST_PORT="${{ env.REST_PORT }}" \
            --env MQS_ADDRESS="${{ env.MQS_ADDRESS }}" \
            --env REST_OPENAPI_SPEC_FPATH="${{ env.REST_OPENAPI_SPEC_FPATH }}" \
            --env DB_JSONSCHEMA_DIR="${{ env.DB_JSONSCHEMA_DIR }}" \
            --env TASKFORCE_LAUNCH_CONTROL_DELAY="${{ env.TASKFORCE_LAUNCH_CONTROL_DELAY }}" \
            --env WORKFLOW_MQ_ACTIVATOR_MQS_RETRY_WAIT="${{ env.WORKFLOW_MQ_ACTIVATOR_MQS_RETRY_WAIT }}" \
            --env WORKFLOW_MQ_ACTIVATOR_DELAY="${{ env.WORKFLOW_MQ_ACTIVATOR_DELAY }}" \
            --env CI="true" \
            ${{ env.CI_DOCKER_IMAGE_W_TAG }} &> ./rest.out &
          
          sleep 10
          export TEST_PILOT_IMAGE_LATEST_TAG=$( python -c 'import requests; print(requests.get("https://api.github.com/repos/Observation-Management-Service/ewms-pilot/releases/latest").json()["tag_name"].lstrip("v"))' )
          pytest -vvv --exitfirst --reverse tests/integration/test_tms_workflow.py
      #
      - if: always()
        run: |
          cat ./dummy_mqs.out
      - if: always()
        run: |
          docker logs rest || cat ./rest.out


  unit-tests:
    needs: [ py-versions, schema-modifications ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py3 }}
      - run: |
          pip install .[tests]
      - name: test
        run: |
          pytest -vvv tests/unit/


  #############################################################################
  # GITHUB RELEASE
  #############################################################################

  release:
    # only run on main/master/default
    if: format('refs/heads/{0}', github.event.repository.default_branch) == github.ref
    needs: [
      flake8,
      mypy,
      py-setup,
      py-versions,
      py-dependencies,
      code-format,
      schema-modifications,
      api-documentation,
      test-build-docker,
      integration-test-full-wms-workflow,
      unit-tests
    ]
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v7.34.6
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # repository_username: __token__
          # repository_password: ${{ secrets.PYPI_TOKEN }}
